const PAYMENT_GATEWAYS = {
  PAYU: 'payu',
  CASHFREE: 'cashfree',
  PHONEPE: 'phonepe'
}

const PAYMENT_PURPOSES = {
  CLIENT_NOTICE: 'CLIENT_NOTICE',
  CLIENT_MEDIATION: 'CLIENT_MEDIATION',
  MEDIATOR_PRO: 'MEDIATOR_PRO'
}

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
}

const PURPOSE_AMOUNTS_INR = {
  [PAYMENT_PURPOSES.CLIENT_NOTICE]: 1000,
  [PAYMENT_PURPOSES.CLIENT_MEDIATION]: 5000
}

module.exports = {
  PAYMENT_GATEWAYS,
  PAYMENT_PURPOSES,
  PAYMENT_STATUS,
  PURPOSE_AMOUNTS_INR
}
