const express = require('express')
const router = express.Router()
const generalController = require('../controller/generalController')
const mediatorController = require('../controller/mediatorController')
const signatureController = require('../controller/signatureController')
const authController = require('../controller/authController')
const blogController = require('../controller/blogController')
const publicProfileController = require('../controller/publicProfileController')
const videoReelController = require('../controller/videoReelController')
const paymentController = require('../controller/paymentController')
const financeController = require('../controller/financeController')
const authMiddleware = require('../middleware/authMiddleware')
const clientController = require('../controller/clientController')
const caseCorrespondenceController = require('../controller/caseCorrespondenceController')
const websiteContactController = require('../controller/websiteContactController')

router.post('/login', authController.login)
router.post('/refresh-token', authController.refreshToken)
router.get('/logout', authController.logout)
router.get('/authenticateWithGoogle', authMiddleware, authController.authenticateWithGoogle)
router.get('/googleCallback', authController.googleCallback)
router.post('/resetPassword', authController.resetPassword)
router.post('/confirmPasswordChange', authController.confirmPasswordChange)
router.post('/sendOtp', authController.sendOtp)
router.post('/verifyOTP', authController.verifyOtp)

router.get('/getUserData', authMiddleware, generalController.getUserData)
router.post('/verify-signature', authMiddleware, generalController.verifySignature)
router.get('/getDashboardContent', authMiddleware, generalController.getDashboardContent)
router.post('/newCalendarEvent', authMiddleware, generalController.newCalendarEvent)
router.post('/saveNote', authMiddleware, generalController.saveNote)
router.post('/deleteNote', authMiddleware, generalController.deleteNote)
router.get('/getCalendarInit', authMiddleware, generalController.getCalendarInit)
router.get('/getPastMediations', authMiddleware, generalController.getPastMediations)
router.post('/newCase', authMiddleware, generalController.newCase)
router.post('/submitEventFeedback', authMiddleware, generalController.submitEventFeedback)
router.post('/markCaseResolved', authMiddleware, generalController.markCaseResolved)
router.get('/getMediationData', authMiddleware, generalController.getMediationData)
router.post('/updateUserProfile', authMiddleware, generalController.updateUserProfile)

router.get('/getAvailableMediators', authMiddleware, mediatorController.getAvailableMediators)
router.post('/assignMediator', authMiddleware, mediatorController.assignMediator)
router.get('/listAllMediatorsWithCases', authMiddleware, mediatorController.listAllMediatorsWithCases)

router.get('/getSignatureRequestDetails', signatureController.getSignatureRequestDetails)
router.post('/submitSignature', signatureController.submitSignature)
router.get('/getAgreementDetailsForSignature', signatureController.getAgreementDetailsForSignature)
router.post('/submitAgreementSignature', signatureController.submitAgreementSignature)

router.get('/getMyBlogs', authMiddleware, blogController.getMyBlogs)
router.get('/getBlogs', blogController.geAllBlogs)
router.get('/getPublicBlogAssets', blogController.getPublicBlogAssets)
router.get('/getBlog', blogController.getBlog)
router.get('/getBlogComments', blogController.getBlogComments)
router.get('/getPublicMediatorProfile', publicProfileController.getPublicMediatorProfile)
router.post('/postBlogComment', authMiddleware, blogController.postBlogComment)
router.post('/saveBlog', authMiddleware, blogController.saveBlog)
router.delete('/deleteBlog/:id', authMiddleware, blogController.deleteBlog)
router.get('/getBlogAssets', blogController.getBlogAssets)
router.get('/blog-taxonomy', authMiddleware, blogController.getAdminBlogTaxonomy)
router.post('/blog-categories', authMiddleware, blogController.createBlogCategory)
router.put('/blog-categories', authMiddleware, blogController.updateBlogCategory)
router.delete('/blog-categories/:id', authMiddleware, blogController.deleteBlogCategory)
router.post('/blog-tags', authMiddleware, blogController.createBlogTag)
router.put('/blog-tags', authMiddleware, blogController.updateBlogTag)
router.delete('/blog-tags/:id', authMiddleware, blogController.deleteBlogTag)

router.get('/getPublicVideoReels', videoReelController.getPublicVideoReels)
router.get('/getMyVideoReels', authMiddleware, videoReelController.getMyVideoReels)
router.post('/saveVideoReel', authMiddleware, videoReelController.saveVideoReel)
router.delete('/deleteVideoReel/:id', authMiddleware, videoReelController.deleteVideoReel)

router.get('/getGoogleToken', authMiddleware, authController.getGoogleToken)

router.post('/newUserSignup', clientController.newUserSignup)
router.post('/newMediatorSignup', mediatorController.newMediatorSignup)
router.post('/updateInactiveUser', authMiddleware, generalController.updateInactiveUser)
router.get('/getAvailableLanguages', generalController.getAvailableLanguages)
router.post('/public/website-contact-lead', websiteContactController.submitPublicLead)
router.get('/isEmailExist', authController.isEmailExist)
router.get('/getInactiveUsers', authMiddleware, generalController.getInactiveUsers)
router.post('/setClientPayment', authMiddleware, paymentController.setClientPayment)
router.get('/getExistingUser', generalController.getExistingUser)
router.post('/acceptMediationRequest', authMiddleware, generalController.acceptMediationRequest)
router.get('/getActiveUsers', authMiddleware, generalController.getActiveUsers)

router.get('/activeCases', authMiddleware, generalController.getAdminActiveCases)
router.get('/caseManagementMeta', authMiddleware, generalController.getAdminCaseManagementMeta)
router.post('/assignCaseMediator', authMiddleware, generalController.adminAssignCaseMediator)
router.get('/users', authMiddleware, generalController.getAdminUsers)
router.post('/users', authMiddleware, generalController.createAdminUser)
router.put('/users', authMiddleware, generalController.updateAdminUser)
router.post('/users/active', authMiddleware, generalController.setAdminActiveStatus)
router.get('/settings', authMiddleware, financeController.getAdminSettings)
router.post('/settings', authMiddleware, financeController.saveAdminSettings)
router.post('/cases/commission', authMiddleware, financeController.updateCaseMediatorCommission)
router.get('/invoices', authMiddleware, financeController.listInvoices)
router.get('/transactions', authMiddleware, financeController.listTransactionsForAdmin)
router.post('/invoices/sync', authMiddleware, financeController.syncMediatorInvoices)
router.post('/invoices/mark-paid', authMiddleware, financeController.markInvoicePaid)
router.get('/invoices/:id/pdf', authMiddleware, financeController.downloadInvoicePdf)
router.get('/mediator-bank-account', authMiddleware, financeController.getMediatorBankAccount)
router.post('/mediator-bank-account', authMiddleware, financeController.saveMediatorBankAccount)

router.get('/case-correspondence', authMiddleware, caseCorrespondenceController.listMessages)
router.post('/case-correspondence', authMiddleware, caseCorrespondenceController.createMessage)
router.get('/admin/case-correspondence', authMiddleware, caseCorrespondenceController.listAllChannelsForAdmin)
router.get('/admin/correspondence/inbox', authMiddleware, caseCorrespondenceController.listInbox)
router.post('/admin/correspondence/inbox/mark-read', authMiddleware, caseCorrespondenceController.markInboxRead)
router.get('/admin/correspondence/context', authMiddleware, caseCorrespondenceController.threadContext)
router.get('/admin/correspondence/cases', authMiddleware, caseCorrespondenceController.listCasesForPicker)
router.get('/admin/website-contact/inbox', authMiddleware, websiteContactController.listInbox)
router.get('/admin/website-contact/thread/:id', authMiddleware, websiteContactController.getThread)
router.post('/admin/website-contact/thread/:id/messages', authMiddleware, websiteContactController.postAdminReply)

router.get('/portal/support/threads', authMiddleware, websiteContactController.listPortalSupportThreads)
router.get('/portal/support/thread/:id', authMiddleware, websiteContactController.getPortalSupportThread)
router.post('/portal/support/thread', authMiddleware, websiteContactController.createPortalSupportThread)
router.post('/portal/support/thread/:id/messages', authMiddleware, websiteContactController.postPortalUserMessage)

router.get('/test', authController.test)

module.exports = router
