const express = require('express')
const router = express.Router()
const generalController = require('../controller/generalController')
const mediatorController = require('../controller/mediatorController')
const signatureController = require('../controller/signatureController')
const authController = require('../controller/authController')
const blogController = require('../controller/blogController')
const videoReelController = require('../controller/videoReelController')
const paymentController = require('../controller/paymentController')
const authMiddleware = require('../middleware/authMiddleware')
const clientController = require('../controller/clientController')

router.post('/login', authController.login)
router.post('/refresh-token', authController.refreshToken)
router.get('/logout', authController.logout)
router.get('/authenticateWithGoogle', authMiddleware, authController.authenticateWithGoogle)
router.get('/googleCallback', authController.googleCallback)
router.post('/resetPassword', authController.resetPassword)
router.post('/confirmPasswordChange', authController.confirmPasswordChange)
router.post('/sendOtp', authController.sendOtp)
router.post('/verifyOTP', authController.verifyOtp)

router.get('/getUserData', authMiddleware, generalController.getUserData)
router.post('/verify-signature', authMiddleware, generalController.verifySignature)
router.get('/getDashboardContent', authMiddleware, generalController.getDashboardContent)
router.post('/newCalendarEvent', authMiddleware, generalController.newCalendarEvent)
router.post('/saveNote', authMiddleware, generalController.saveNote)
router.post('/deleteNote', authMiddleware, generalController.deleteNote)
router.get('/getCalendarInit', authMiddleware, generalController.getCalendarInit)
router.get('/getMyCases', authMiddleware, generalController.getMyCases)
router.post('/newCase', authMiddleware, generalController.newCase)
router.post('/submitEventFeedback', authMiddleware, generalController.submitEventFeedback)
router.post('/markCaseResolved', authMiddleware, generalController.markCaseResolved)
router.get('/getMediationData', authMiddleware, generalController.getMediationData)
router.post('/updateUserProfile', authMiddleware, generalController.updateUserProfile)

router.get('/getAvailableMediators', authMiddleware, mediatorController.getAvailableMediators)
router.post('/assignMediator', authMiddleware, mediatorController.assignMediator)
router.get('/listAllMediatorsWithCases', authMiddleware, mediatorController.listAllMediatorsWithCases)

router.get('/getSignatureRequestDetails', signatureController.getSignatureRequestDetails)
router.post('/submitSignature', signatureController.submitSignature)
router.get('/getAgreementDetailsForSignature', signatureController.getAgreementDetailsForSignature)
router.post('/submitAgreementSignature', signatureController.submitAgreementSignature)

router.get('/getMyBlogs', authMiddleware, blogController.getMyBlogs)
router.get('/getBlogs', blogController.geAllBlogs)
router.get('/getPublicBlogAssets', blogController.getPublicBlogAssets)
router.get('/getBlog', blogController.getBlog)
router.post('/saveBlog', authMiddleware, blogController.saveBlog)
router.delete('/deleteBlog/:id', authMiddleware, blogController.deleteBlog)
router.get('/getBlogAssets', blogController.getBlogAssets)

router.get('/getPublicVideoReels', videoReelController.getPublicVideoReels)
router.get('/getMyVideoReels', authMiddleware, videoReelController.getMyVideoReels)
router.post('/saveVideoReel', authMiddleware, videoReelController.saveVideoReel)
router.delete('/deleteVideoReel/:id', authMiddleware, videoReelController.deleteVideoReel)

router.get('/getGoogleToken', authMiddleware, authController.getGoogleToken)

router.post('/newUserSignup', clientController.newUserSignup)
router.post('/newMediatorSignup', mediatorController.newMediatorSignup)
router.post('/updateInactiveUser', authMiddleware, generalController.updateInactiveUser)
router.get('/getAvailableLanguages', generalController.getAvailableLanguages)
router.get('/isEmailExist', authController.isEmailExist)
router.get('/getInactiveUsers', authMiddleware, generalController.getInactiveUsers)
router.post('/setClientPayment', authMiddleware, paymentController.setClientPayment)
router.get('/getExistingUser', generalController.getExistingUser)
router.post('/acceptMediationRequest', authMiddleware, generalController.acceptMediationRequest)
router.get('/getActiveUsers', authMiddleware, generalController.getActiveUsers)

router.get('/activeCases', authMiddleware, generalController.getAdminActiveCases)
router.get('/caseManagementMeta', authMiddleware, generalController.getAdminCaseManagementMeta)
router.post('/assignCaseMediator', authMiddleware, generalController.adminAssignCaseMediator)

router.get('/test', authController.test)

module.exports = router
