const express = require('express')
const generalController = require('../../controller/generalController')
const financeController = require('../../controller/financeController')
const rewardController = require('../../controller/rewardController')
const mediatorAdminController = require('../../controller/mediatorAdminController')
const premiumAdminController = require('../../controller/premiumAdminController')
const caseCorrespondenceController = require('../../controller/caseCorrespondenceController')
const websiteContactController = require('../../controller/websiteContactController')
const notificationAdminController = require('../../controller/notificationAdminController')
const websiteContentController = require('../../controller/websiteContentController')
const blogController = require('../../controller/blogController')
const couponController = require('../../controller/couponController')
const authMiddleware = require('../../middleware/authMiddleware')
const { requireAdmin } = require('../../middleware/requireRole')
const { auditMiddleware, AUDIT_ACTIONS } = require('../../services/audit/auditLogService')

const router = express.Router()

// Auth only at router level — role checks must be per-route.
// A blanket requireAdmin would 403 non-admins for unmatched paths (and block fall-through).
router.use(authMiddleware)

router.get('/getInactiveUsers', requireAdmin, generalController.getInactiveUsers)
router.post('/updateInactiveUser', requireAdmin, auditMiddleware(AUDIT_ACTIONS.USER_ACTIVATED, { targetType: 'user', getTargetId: (req) => req.body.userId, getDetails: (req) => ({ isActive: req.body.isActive }) }), generalController.updateInactiveUser)
router.post('/admin/setUserDeleted', requireAdmin, auditMiddleware(AUDIT_ACTIONS.USER_DELETED, { targetType: 'user', getTargetId: (req) => req.body.userId }), generalController.adminSetUserDeleted)
router.get('/getActiveUsers', requireAdmin, generalController.getActiveUsers)
router.get('/users', requireAdmin, generalController.getAdminUsers)
router.post('/users', requireAdmin, auditMiddleware(AUDIT_ACTIONS.USER_CREATED, { targetType: 'admin_user' }), generalController.createAdminUser)
router.put('/users', requireAdmin, auditMiddleware(AUDIT_ACTIONS.USER_UPDATED, { targetType: 'admin_user', getTargetId: (req) => req.body.id }), generalController.updateAdminUser)
router.post('/users/active', requireAdmin, auditMiddleware(AUDIT_ACTIONS.USER_DEACTIVATED, { targetType: 'admin_user', getTargetId: (req) => req.body.id }), generalController.setAdminActiveStatus)

router.get('/settings', requireAdmin, financeController.getAdminSettings)
router.post('/settings', requireAdmin, auditMiddleware(AUDIT_ACTIONS.SETTINGS_CHANGED, { targetType: 'settings' }), financeController.saveAdminSettings)
router.post('/cases/commission', requireAdmin, auditMiddleware(AUDIT_ACTIONS.CASE_COMMISSION_CHANGED, { targetType: 'case', getTargetId: (req) => req.body.caseId }), financeController.updateCaseMediatorCommission)
router.get('/transactions', requireAdmin, financeController.listTransactionsForAdmin)
router.post('/invoices/sync', requireAdmin, financeController.syncMediatorInvoices)
router.post('/invoices/mark-paid', requireAdmin, auditMiddleware(AUDIT_ACTIONS.INVOICE_PAID, { targetType: 'invoice', getTargetId: (req) => req.body.invoiceId }), financeController.markInvoicePaid)

router.get('/admin/mediator/rewards', requireAdmin, rewardController.getMediatorRewardsAdmin)
router.get('/admin/reward-catalog', requireAdmin, rewardController.getRewardCatalogAdmin)
router.post('/admin/reward-catalog', requireAdmin, rewardController.saveRewardCatalogItem)
router.delete('/admin/reward-catalog/:id', requireAdmin, rewardController.deleteRewardCatalogItem)
router.get('/admin/reward-orders', requireAdmin, rewardController.getRewardOrdersAdmin)
router.post('/admin/reward-orders/:id/fulfill', requireAdmin, rewardController.fulfillRewardOrder)
router.get('/admin/reward-fulfillment-catalog', requireAdmin, premiumAdminController.getFulfillmentCatalog)
router.get('/admin/reward-fulfillment-rules', requireAdmin, premiumAdminController.listFulfillmentRules)
router.get('/admin/reward-fulfillment-rules/:id', requireAdmin, premiumAdminController.getFulfillmentRule)
router.post('/admin/reward-fulfillment-rules', requireAdmin, premiumAdminController.saveFulfillmentRule)
router.delete('/admin/reward-fulfillment-rules/:id', requireAdmin, premiumAdminController.deleteFulfillmentRule)

router.get('/admin/mediators/:mediatorId/offboarding-preview', requireAdmin, mediatorAdminController.getOffboardingPreview)
router.post('/admin/mediators/:mediatorId/complete-offboarding', requireAdmin, auditMiddleware(AUDIT_ACTIONS.MEDIATOR_OFFBOARDED, { targetType: 'mediator', getTargetId: (req) => req.params.mediatorId }), mediatorAdminController.completeOffboarding)
router.get('/admin/mediators/:mediatorId/360', requireAdmin, mediatorAdminController.getMediator360)
router.get('/admin/premium-features', requireAdmin, premiumAdminController.listPremiumFeatures)
router.post('/admin/premium-features', requireAdmin, premiumAdminController.updatePremiumFeature)

router.get('/admin/coupons', requireAdmin, couponController.listCoupons)
router.post('/admin/coupons', requireAdmin, auditMiddleware(AUDIT_ACTIONS.SETTINGS_CHANGED, { targetType: 'coupon' }), couponController.createCoupon)
router.delete('/admin/coupons/:id', requireAdmin, auditMiddleware(AUDIT_ACTIONS.SETTINGS_CHANGED, { targetType: 'coupon', getTargetId: (req) => req.params.id }), couponController.deleteCoupon)

router.get('/admin/case-correspondence', requireAdmin, caseCorrespondenceController.listAllChannelsForAdmin)
router.get('/admin/correspondence/inbox', requireAdmin, caseCorrespondenceController.listInbox)
router.post('/admin/correspondence/inbox/mark-read', requireAdmin, caseCorrespondenceController.markInboxRead)
router.get('/admin/correspondence/context', requireAdmin, caseCorrespondenceController.threadContext)
router.get('/admin/correspondence/cases', requireAdmin, caseCorrespondenceController.listCasesForPicker)
router.get('/admin/website-contact/inbox', requireAdmin, websiteContactController.listInbox)
router.get('/admin/website-contact/thread/:id', requireAdmin, websiteContactController.getThread)
router.post('/admin/website-contact/thread/:id/messages', requireAdmin, websiteContactController.postAdminReply)

router.get('/admin/notifications/templates', requireAdmin, notificationAdminController.listTemplates)
router.post('/admin/notifications/templates', requireAdmin, notificationAdminController.saveTemplate)
router.delete('/admin/notifications/templates/:id', requireAdmin, notificationAdminController.deleteTemplate)
router.post('/admin/notifications/templates/preview', requireAdmin, notificationAdminController.previewTemplate)
router.get('/admin/notifications/channel-settings', requireAdmin, notificationAdminController.listChannelSettings)
router.post('/admin/notifications/channel-settings', requireAdmin, notificationAdminController.saveChannelSettings)
router.get('/admin/notifications/users', requireAdmin, notificationAdminController.searchUsers)
router.post('/admin/notifications/send', requireAdmin, notificationAdminController.sendBulk)
router.get('/admin/notifications/send-logs', requireAdmin, notificationAdminController.listSendLogs)
router.post('/admin/notifications/preview-email-layout', requireAdmin, notificationAdminController.previewEmailLayout)

router.get('/admin/website-content', requireAdmin, websiteContentController.getContent)
router.put('/admin/website-content/settings', requireAdmin, websiteContentController.saveSettings)
router.put('/admin/website-content/banner', requireAdmin, websiteContentController.saveBanner)
router.post('/admin/website-content/testimonials', requireAdmin, websiteContentController.saveTestimonial)
router.delete('/admin/website-content/testimonials/:id', requireAdmin, websiteContentController.deleteTestimonial)
router.post('/admin/website-content/pricing-plans', requireAdmin, websiteContentController.savePricingPlan)
router.delete('/admin/website-content/pricing-plans/:id', requireAdmin, websiteContentController.deletePricingPlan)
router.post('/admin/website-content/faq-categories', requireAdmin, websiteContentController.saveFaqCategory)
router.delete('/admin/website-content/faq-categories/:id', requireAdmin, websiteContentController.deleteFaqCategory)
router.post('/admin/website-content/faq-items', requireAdmin, websiteContentController.saveFaqItem)
router.delete('/admin/website-content/faq-items/:id', requireAdmin, websiteContentController.deleteFaqItem)
router.post('/admin/website-content/regenerate', requireAdmin, websiteContentController.regenerate)

router.get('/blog-taxonomy', requireAdmin, blogController.getAdminBlogTaxonomy)
router.post('/blog-categories', requireAdmin, blogController.createBlogCategory)
router.put('/blog-categories', requireAdmin, blogController.updateBlogCategory)
router.delete('/blog-categories/:id', requireAdmin, blogController.deleteBlogCategory)
router.post('/blog-tags', requireAdmin, blogController.createBlogTag)
router.put('/blog-tags', requireAdmin, blogController.updateBlogTag)
router.delete('/blog-tags/:id', requireAdmin, blogController.deleteBlogTag)

module.exports = router
